### ISSUE TITLE
Seems to be too outdated to work with source Files from an Android 5 Lollipop

### ISSUE THREAD

**Issue by porg** [abbot/android-restore-tools#4]
Source files: Android 5 Lollipop (a Cyanogen Mod which ran on a Samsung S3 Neo)
macOS 10.12.6
Python 2.7.10

```
$ ./mmssms2xml.py ~/mmssms.db 
Traceback (most recent call last):
  File "./mmssms2xml.py", line 152, in <module>
    cli()
  File "./mmssms2xml.py", line 71, in cli
    messages = read_messages(args[0])
  File "./mmssms2xml.py", line 33, in read_messages
    c.execute("SELECT _id, thread_id, address, person, date, protocol, read, priority, status, type, callback_number, reply_path_present, subject, body, service_center, failure_cause, locked, error_code, stack_type, seen, sort_index FROM sms ORDER BY date DESC")
sqlite3.OperationalError: no such column: callback_number
```

```
$ ./calllog2xml.py ~/telephony.db 
Traceback (most recent call last):
  File "./calllog2xml.py", line 105, in <module>
    cli()
  File "./calllog2xml.py", line 24, in cli
    calls = read_calls(args[0])
  File "~/bin/bin/android-restore-tools/convert.py", line 29, in read_calls
    c.execute("SELECT COUNT(*) FROM calls")
sqlite3.OperationalError: no such table: calls
```

**Comment by porg** [comment]
Good news:

1) For **calllog2xml.py** I have chosen the wrong input file **telephony.db**. With **contacts2.db** it worked.
```
./calllog2xml.py ~/contacts2.db 
Read 500 calls
Call logs saved to calls-<YYYYMMDDhhmmss>.xml.
Now copy this file to your SD Card into 
CallLogBackupRestore folder and use Call Logs Backup & Restore by Ritesh Sahu
to restore your call logs.
Google Play store link to the app (free version): http://goo.gl/ZO5cy
```

2) With **mmssms2xml.py** I was not lucky. But I found a working alternative:
https://github.com/t413/SMS-Tools

So after all I could both restore my call log and sms archive.
